#!/usr/bin/env bash

echo "Installing rbenv for managing Ruby versions."
git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
exec $SHELL -l

echo "Installing ruby-build as an rbenv plugin."
git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins

echo "Installing Ruby 1.9.3-p392. This will take awhile..."
rbenv install 1.9.3-p392
rbenv rehash
rbenv global 1.9.3-p392

echo "Updating RubyGems and default gems for Ruby" `rbenv global` "."
gem update --system
gem update
rbenv rehash

echo "Installing latest Bundler gem."
gem install bundler
rbenv rehash

echo "Installing latest Rake gem."
gem install rake
rbenv rehash

echo "Installing MyFDB utilities gem for image uploads."
git clone git@github.com:MyFDB/myfdb_utilities.git ~/myfdb_utilities
cd ~/myfdb_utilities
gem build myfdb_utilities.gemspec
gem install myfdb_utilities-0.0.6.gem
rbenv rehash
